/** Formats FFmpeg can decode but not reliably encode as output. */
export const AUDIO_OUTPUT_SKIP = new Set(["ape", "mid", "midi"]);
export const VIDEO_OUTPUT_SKIP = new Set(["rm", "swf"]);
export const AUDIO_FORMATS = new Set([
  "mp3", "wav", "flac", "aac", "ogg", "m4a", "wma", "opus", "aiff", "aif",
  "amr", "ac3", "au", "caf", "mka", "wv", "ape", "dts", "mid", "midi", "voc",
]);

export const VIDEO_FORMATS = new Set([
  "mp4", "webm", "avi", "mov", "mkv", "wmv", "flv", "m4v", "mpg", "mpeg",
  "3gp", "3g2", "ogv", "ts", "mts", "m2ts", "vob", "asf", "rm", "f4v",
  "dv", "mxf", "ogm", "m2v", "nut", "swf", "hevc", "mod",
]);

export const MEDIA_MIME = {
  mp3: "audio/mpeg",
  wav: "audio/wav",
  flac: "audio/flac",
  aac: "audio/aac",
  ogg: "audio/ogg",
  m4a: "audio/mp4",
  wma: "audio/x-ms-wma",
  opus: "audio/opus",
  aiff: "audio/aiff",
  aif: "audio/aiff",
  amr: "audio/amr",
  ac3: "audio/ac3",
  au: "audio/basic",
  caf: "audio/x-caf",
  mka: "audio/x-matroska",
  wv: "audio/x-wavpack",
  ape: "audio/x-ape",
  dts: "audio/vnd.dts",
  mid: "audio/midi",
  midi: "audio/midi",
  voc: "audio/x-voc",
  mp4: "video/mp4",
  webm: "video/webm",
  avi: "video/x-msvideo",
  mov: "video/quicktime",
  mkv: "video/x-matroska",
  wmv: "video/x-ms-wmv",
  flv: "video/x-flv",
  m4v: "video/x-m4v",
  mpg: "video/mpeg",
  mpeg: "video/mpeg",
  "3gp": "video/3gpp",
  "3g2": "video/3gpp2",
  ogv: "video/ogg",
  ts: "video/mp2t",
  mts: "video/mp2t",
  m2ts: "video/mp2t",
  vob: "video/dvd",
  asf: "video/x-ms-asf",
  rm: "application/vnd.rn-realmedia",
  f4v: "video/x-f4v",
  dv: "video/dv",
  mxf: "application/mxf",
  ogm: "video/ogg",
  m2v: "video/mpeg",
  nut: "video/x-nut",
  swf: "application/x-shockwave-flash",
  hevc: "video/hevc",
  mod: "video/mpeg",
};
